FROM scratch
MAINTAINER Leonardo Loures <luvres@hotmail.com>

# Mini Root Filesystem
# http://cdimage.ubuntu.com/ubuntu-base/releases/xenial/release/ubuntu-base-16.04.3-base-armhf.tar.gz
ADD ubuntu-base-16.04.3-base-armhf.tar.gz /
CMD ["/bin/bash"]
