FROM scratch
MAINTAINER Leonardo Loures <luvres@hotmail.com>

# Mini Root Filesystem
# http://cdimage.ubuntu.com/ubuntu-base/releases/precise/release/ubuntu-base-12.04.5-core-armhf.tar.gz
ADD ubuntu-base-14.04.5-base-armhf.tar.gz
CMD ["/bin/bash"]
