FROM scratch
MAINTAINER Leonardo Loures <luvres@hotmail.com>
#LABEL architecture="ARMv7"

# Mini Root Filesystem
# https://nl.alpinelinux.org/alpine/v3.8/releases/armhf/
ADD alpine-minirootfs-3.8.0-armhf.tar.gz /

CMD ["/bin/sh"]
